import { createContext } from "react"

const GlobalContext = createContext({
	dayIndex: 0,
	setDayIndex: () => {},
	daySelected: null,
	setDaySelected: () => {},
	showEventModal: false,
	setShowEventModal: () => {},
	showEventButton: false,
	setShowEventButton: () => {},
	showEventLogo: false,
	setShowEventLogo: () => {},
	showEventBox: false,
	setShowEventBox: () => {},
	showEventFooter: false,
	setShowEventFooter: () => {},
	showEventSocialNetwork: false,
	setShowEventSocialNetwork: () => {},
	showEventTitle: false,
	setShowEventTitle: () => {},
	imageLogo: null,
	setImageLogo: () => {},
	IDimage: "",
	setIDimage: () => {},
	homeImageID: "",
	setHomeImageID: () => {},
	nameForm: "",
	setNameForm: () => {},
	descriptionForm: "",
	setDescriptionForm: () => {},
	colorForm: "",
	setColorForm: () => {},
	bgColorForm: "",
	setBgColorForm: () => {},
	fontForm: "",
	setFontForm: () => {},
	iconForm: "",
	setIconForm: () => {},
	titleForm: "",
	setTitleForm: () => {},
	paragraphForm: "",
	setParagraphForm: () => {},
	userData: "",
	setUserData: () => {},
})

export default GlobalContext
